<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ssGrupo</groupId>
        <artifactId>sanosSalvos_parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <groupId>ssGrupo</groupId>
    <artifactId>infraestructura</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>ServidorEureka</module>
        <module>SpringbootAdmin</module>
        <module>APIGateway</module>
    </modules>
    
</project>