server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: mascota_gateway
          uri: lb://mascota
          predicates:
            - Path=/mascota/**
            
        - id: usuario_gateway
          uri: lb://usuario
          predicates:
            - Path=/usuario/**
            
        - id: reporte_gateway
          uri: lb://reporte
          predicates:
            - Path=/reporte/**
            
        - id: mCoincidencias_gateway
          uri: lb://mCoincidencias
          predicates:
            - Path=/motor/**